# Generated by Django 3.2.6 on 2025-03-13 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('tipo_sangre', models.CharField(max_length=500)),
                ('rh', models.CharField(max_length=500)),
                ('cedula', models.CharField(max_length=500)),
                ('alergias', models.CharField(max_length=500)),
                ('eps', models.CharField(max_length=500)),
                ('telefono', models.CharField(max_length=500)),
            ],
        ),
    ]
